version: '3'
services:
  master-bot:
    platform: 'linux/amd64'
    env_file:
      - .env
      - docker.env
    restart: always
    build: .
    ports:
      - '3000:3000' # Dashboard & Health
      # - "5555:5555" # Prisma Studio Port  - uncomment to open
    command: >
      sh -c "pnpm run db:push && pnpm start"
    depends_on:
      lavalink:
        condition: service_healthy
    links:
      - lavalink
    volumes:
      - ./logs:/Master-Bot/logs
      - sqlite-data:/Master-Bot/packages/db/prisma
  lavalink:
    restart: always
    image: ghcr.io/lavalink-devs/lavalink:4-alpine
    healthcheck:
      test: 'echo lavalink'
      interval: 10s
      timeout: 10s
      retries: 3
    volumes:
      - ./application.yml:/opt/Lavalink/application.yml
volumes:
  sqlite-data:
    driver: local