version: '3.8'
services:
  master-bot:
    container_name: master-bot
    platform: 'linux/amd64'
    env_file:
      - .env
    restart: always
    build: .
    ports:
      - '3000:3000' # Web Dashboard
      - '3001:3001' # Bot Gateway / Client
      - '3002:3002' # Bot Internal HTTP API
    command: >
      sh -c "pnpm db:push && pnpm start"
    depends_on:
      lavalink:
        condition: service_healthy
    volumes:
      - ./data:/app/packages/db/prisma
      - ./logs:/app/logs
  lavalink:
    container_name: master-bot-lavalink
    restart: always
    image: ghcr.io/lavalink-devs/lavalink:4-alpine
    ports:
      - '2333:2333'
    healthcheck:
      test: ['CMD', 'wget', '--spider', '-q', 'http://localhost:2333/version']
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./application.yml:/opt/Lavalink/application.yml
